# Generated by Django 3.0.6 on 2022-05-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='spam_count',
            field=models.IntegerField(default=0),
        ),
    ]
